server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: eureka
      password: admin

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-server-port: 8761
  instance:
    hostname: localhost