server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
