openapi: 3.0.1
info:
  title: User API
  description: API for managing user data
  version: 0.0.1
servers:
- url: http://localhost:8010
tags:
- name: User
  description: User related resource
paths:
  /api/v1:
    post:
      tags:
      - User
      summary: Create user
      description: Create a User with given input
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
        required: true
      responses:
        "204":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRepresentation'
        "400":
          description: Bad request. Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/{username}:
    get:
      tags:
      - User
      summary: Get user
      description: Get the user by its username
      operationId: getUserByUsername
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: User was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        "200":
          description: User was found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRepresentation'
components:
  schemas:
    CreateUserInput:
      required:
      - email
      - username
      type: object
      properties:
        username:
          type: string
        realName:
          type: string
        email:
          type: string
    UserRepresentation:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        realName:
          type: string
    ApiError:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        code:
          type: integer
          format: int32
        status:
          type: string
        message:
          type: string
        errors:
          type: array
          items:
            type: string
